#!/bin/bash
# Powerlevel10k Installer
# Installs Powerlevel10k theme for Zsh with optimized configuration

# Source required libraries
if [[ -z "${SCRIPT_DIR:-}" ]]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
fi
source "$SCRIPT_DIR/core/lib/colors.sh"
source "$SCRIPT_DIR/core/lib/error-handler.sh"
source "$SCRIPT_DIR/core/lib/validation.sh"
source "$SCRIPT_DIR/core/lib/common.sh"

# Install Powerlevel10k
install_powerlevel10k() {
    print_section "Installing Powerlevel10k theme"

    # Check if zsh is installed
    if ! command_exists zsh; then
        print_error "Zsh is required. Please install Zsh first."
        return 1
    fi

    # Check if git is available
    if ! command_exists git; then
        print_error "Git is required to clone Powerlevel10k"
        return 1
    fi

    local p10k_dir="${HOME}/.local/share/fonts/powerlevel10k"
    local p10k_repo_dir="${HOME}/.config/powerlevel10k"

    # Create directory for Powerlevel10k
    mkdir -p "$p10k_repo_dir"

    # Check if already installed
    if [[ -d "$p10k_repo_dir/powerlevel10k" ]]; then
        print_info "Powerlevel10k already installed"
        return 0
    fi

    # Clone Powerlevel10k repository
    print_info "Cloning Powerlevel10k repository..."
    if ! git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$p10k_repo_dir/powerlevel10k" 2>/dev/null; then
        print_error "Failed to clone Powerlevel10k repository"
        return 1
    fi

    # Install recommended fonts
    print_info "Installing recommended fonts..."
    mkdir -p "$p10k_dir"

    # Download MesloLGS NerdFont
    local font_dir="$p10k_dir/fonts"
    mkdir -p "$font_dir"

    # Install fonts from Powerlevel10k repo
    if [[ -d "$p10k_repo_dir/powerlevel10k/font" ]]; then
        cp "$p10k_repo_dir/powerlevel10k/font/"* "$font_dir/" 2>/dev/null || true
        print_ok "Fonts installed to $font_dir"
    fi

    print_ok "Powerlevel10k installation complete"
    echo ""

    return 0
}

# Generate .p10k.zsh configuration
generate_p10k_config() {
    local config_file="${HOME}/.p10k.zsh"
    local username=${1:-$(whoami)}

    print_section "Generating Powerlevel10k configuration"

    # Create optimized .p10k.zsh
    cat > "$config_file" << 'EOFP10K'
# Powerlevel10k Configuration
# Generated by shell configuration setup

# Instant prompt. Should stay close to the top of ~/.zshrc.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Prompt segment configuration
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon
    dir
    vcs
    command_execution_time
    status
    command_number
)

typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    time
    background_jobs
)

# Directory
typeset -g POWERLEVEL9K_DIR_FOREGROUND=4
typeset -g POWERLEVEL9K_DIR_HOME_FOREGROUND=4
typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND=4
typeset -g POWERLEVEL9K_DIR_ETC_FOREGROUND=1

# VCS (Git/Hg/Svn)
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=2
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=2
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=3
typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=1

# Git
typeset -g POWERLEVEL9K_VCS_GIT_GITHUB_ICON=''
typeset -g POWERLEVEL9K_VCS_GIT_GITLAB_ICON=''
typeset -g POWERLEVEL9K_VCS_GIT_ICON='󰊢'

# Status
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=2
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=1
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=1

# Time
typeset -g POWERLEVEL9K_TIME_FOREGROUND=8
typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'

# Command execution time
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=3
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3

# Transient prompt (simplified prompt on previous lines)
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT_IN_SELECT_PMODE=false
typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

# Remove newline before prompt
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false

# Connect prompt segments
typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''

# Separator between segments
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=' '
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=' '

# Debug
[[ ! -v POWERLEVEL9K_DEBUG ]] && POWERLEVEL9K_DEBUG=off
EOFP10K

    print_ok "Configuration saved to $config_file"
    echo ""

    return 0
}

# Get Powerlevel10k installation status
get_powerlevel10k_status() {
    if [[ -d "${HOME}/.config/powerlevel10k/powerlevel10k" ]]; then
        echo "installed"
    else
        echo "not-installed"
    fi
}

# Verify Powerlevel10k installation
verify_powerlevel10k() {
    print_section "Verifying Powerlevel10k Installation"

    local all_ok=true

    # Check theme directory
    if [[ -d "${HOME}/.config/powerlevel10k/powerlevel10k" ]]; then
        print_ok "Powerlevel10k theme: installed"
    else
        print_warning "Powerlevel10k theme: not found"
        all_ok=false
    fi

    # Check configuration
    if [[ -f "${HOME}/.p10k.zsh" ]]; then
        print_ok "Configuration file: ~/.p10k.zsh"
    else
        print_warning "Configuration file: not found"
        all_ok=false
    fi

    # Check Zsh integration
    if grep -q "powerlevel10k" "${HOME}/.zshrc" 2>/dev/null; then
        print_ok "Zsh integration: enabled"
    else
        print_warning "Zsh integration: not configured"
        all_ok=false
    fi

    echo ""

    if $all_ok; then
        print_ok "Powerlevel10k is fully installed"
        return 0
    else
        print_warning "Powerlevel10k setup incomplete"
        return 1
    fi
}

# Export functions
export -f install_powerlevel10k
export -f generate_p10k_config
export -f get_powerlevel10k_status
export -f verify_powerlevel10k
