#!/bin/bash
# Shell Configuration Manager
# Sets up Zsh with Powerlevel10k, aliases, and environment variables

# Source required libraries
if [[ -z "${PROJECT_ROOT:-}" ]]; then
    # Get project root: from core/shells/ go up two levels
    PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
fi
source "$PROJECT_ROOT/core/lib/colors.sh"
source "$PROJECT_ROOT/core/lib/error-handler.sh"
source "$PROJECT_ROOT/core/lib/validation.sh"
source "$PROJECT_ROOT/core/lib/common.sh"

# Source shell installers
source "$PROJECT_ROOT/core/shells/zsh-installer.sh"
source "$PROJECT_ROOT/core/shells/powerlevel10k-installer.sh"

# Setup shell environment
setup_shell_environment() {
    print_section "Setting up shell environment"

    local zshrc="${HOME}/.zshrc"
    local backup_suffix=".backup.$(date +%s)"

    # Create backup of existing zshrc if it exists
    if [[ -f "$zshrc" ]]; then
        print_info "Backing up existing ~/.zshrc to ~/.zshrc$backup_suffix"
        cp "$zshrc" "$zshrc$backup_suffix"
    fi

    # Create new .zshrc with Powerlevel10k integration
    print_info "Creating ~/.zshrc with Powerlevel10k integration..."

    cat > "$zshrc" << 'EOFZSHRC'
# Zsh Configuration with Powerlevel10k
# Auto-generated by shell configuration setup

# Enable Powerlevel10k instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Load Powerlevel10k
if [[ -d "$HOME/.config/powerlevel10k/powerlevel10k" ]]; then
    source "$HOME/.config/powerlevel10k/powerlevel10k/powerlevel10k.zsh-theme"
fi

# Load Powerlevel10k configuration
if [[ -f ~/.p10k.zsh ]]; then
    source ~/.p10k.zsh
fi

# History configuration
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_FIND_NO_DUPS

# Completion configuration
autoload -Uz compinit
compinit
setopt MENU_COMPLETE
zstyle ':completion:*' menu select

# Enable command substitution in prompts
setopt PROMPT_SUBST

# Keybindings
bindkey '^[[A' history-search-backward
bindkey '^[[B' history-search-forward
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line

# Aliases
alias ll='ls -lah'
alias la='ls -la'
alias l='ls -lh'
alias ..='cd ..'
alias ...='cd ../..'
alias grep='grep --color=auto'
alias mkdir='mkdir -pv'

# Bat alias for cat if available
if command -v bat &> /dev/null; then
    alias cat='bat'
fi

# Git aliases
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline -10'
alias gd='git diff'

# Docker aliases (if docker is installed)
if command -v docker &> /dev/null; then
    alias dps='docker ps'
    alias di='docker images'
    alias dls='docker ps -a'
fi

# Python aliases
if command -v python3 &> /dev/null; then
    alias python='python3'
    alias pip='pip3'
fi

# Node.js aliases
if command -v node &> /dev/null; then
    alias n='npm'
    alias ni='npm install'
    alias nr='npm run'
fi

# Source local customizations if they exist
if [[ -f ~/.zshrc.local ]]; then
    source ~/.zshrc.local
fi

# Environment variables
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export EDITOR=nano
export VISUAL=nano

# Add user local bin to PATH if it exists
if [[ -d "$HOME/.local/bin" ]]; then
    export PATH="$HOME/.local/bin:$PATH"
fi

# Color support for ls
if [[ -f ~/.dircolors ]]; then
    eval "$(dircolors -b ~/.dircolors)"
else
    eval "$(dircolors -b)"
fi
EOFZSHRC

    print_ok "~/.zshrc created successfully"
    echo ""

    return 0
}

# Install complete shell environment
install_shell_environment() {
    print_section "Installing complete shell environment"

    # Install Zsh
    print_subsection "Step 1: Installing Zsh"
    if ! install_zsh; then
        print_warning "Zsh installation failed, but continuing..."
    fi
    echo ""

    # Install Powerlevel10k
    print_subsection "Step 2: Installing Powerlevel10k"
    if ! install_powerlevel10k; then
        print_warning "Powerlevel10k installation failed, but continuing..."
    fi
    echo ""

    # Generate configuration
    print_subsection "Step 3: Generating Powerlevel10k configuration"
    if ! generate_p10k_config; then
        print_warning "Configuration generation failed"
        return 1
    fi
    echo ""

    # Setup shell environment
    print_subsection "Step 4: Setting up shell configuration"
    if ! setup_shell_environment; then
        print_warning "Shell configuration failed"
        return 1
    fi
    echo ""

    # Set Zsh as default shell (optional)
    print_subsection "Step 5: Setting Zsh as default shell"
    if command_exists zsh; then
        if set_zsh_default "$(whoami)"; then
            print_ok "Zsh set as default shell"
        else
            print_info "Note: To set Zsh as default, run: chsh -s $(command -v zsh)"
        fi
    fi
    echo ""

    print_ok "Shell environment setup complete!"
    echo ""
    print_info "Next steps:"
    echo "  1. Restart your terminal or run: exec zsh"
    echo "  2. Customize shell settings in ~/.zshrc.local"
    echo "  3. For Powerlevel10k configuration, run: p10k configure"

    return 0
}

# Verify shell environment
verify_shell_environment() {
    print_section "Verifying Shell Environment"

    local all_ok=true

    # Check Zsh
    if command_exists zsh; then
        local zsh_version
        zsh_version=$(zsh --version)
        print_ok "Zsh: $zsh_version"
    else
        print_warning "Zsh not found"
        all_ok=false
    fi

    # Check Powerlevel10k
    if [[ -d "${HOME}/.config/powerlevel10k/powerlevel10k" ]]; then
        print_ok "Powerlevel10k: installed"
    else
        print_warning "Powerlevel10k not found"
        all_ok=false
    fi

    # Check .zshrc
    if [[ -f "${HOME}/.zshrc" ]]; then
        print_ok ".zshrc: configured"
    else
        print_warning ".zshrc not found"
        all_ok=false
    fi

    # Check .p10k.zsh
    if [[ -f "${HOME}/.p10k.zsh" ]]; then
        print_ok ".p10k.zsh: configured"
    else
        print_warning ".p10k.zsh not found"
        all_ok=false
    fi

    echo ""

    if $all_ok; then
        print_ok "Shell environment is fully configured"
        return 0
    else
        print_warning "Shell environment is incomplete"
        return 1
    fi
}

# Export functions
export -f setup_shell_environment
export -f install_shell_environment
export -f verify_shell_environment
